const rows = [
  {
    id: 1,
    photo: "https://i.imgur.com/Svn8iB3.jpeg",
    name: "Abel Espinoza",
    adress: "Calle 1",
    city: "Culiacan",
    state: "Sinaloa",
    age: 20,
    rate: 4.5,
  },
  {
    id: 2,
    photo: "https://i.imgur.com/pBcut2e.jpeg",
    name: "Omar Vega",
    adress: "Calle 2",
    city: "Hermosillo",
    state: "Sonora",
    age: 20,
    rate: 4.5,
  },
  {
    id: 3,
    photo: "https://i.imgur.com/Svn8iB3.jpeg",
    name: "Abel Espinoza",
    adress: "Calle 3",
    city: "Ciudad Juarez",
    state: "Chihuahua",
    age: 20,
    rate: 4.5,
  },
  {
    id: 4,
    photo: "https://i.imgur.com/pBcut2e.jpeg",
    name: "Jesus Quintero",
    adress: "Calle 4",
    city: "Culiacan",
    state: "Sinaloa",
    age: 20,
    rate: 4.5,
  },
  {
    id: 5,
    photo: "https://i.imgur.com/Svn8iB3.jpeg",
    name: "Cesar Sainz",
    adress: "Calle 5",
    city: "Hermosillo",
    state: "Sonora",
    age: 20,
    rate: 4.5,
  },
  {
    id: 6,
    photo: "https://i.imgur.com/pBcut2e.jpeg",
    name: "Jorge Razo",
    adress: "Calle 6",
    city: "Ciudad Juarez",
    state: "Chihuahua",
    age: 20,
    rate: 4.5,
  },
];

export default rows;
